### ISSUE TITLE
findNLDI() doesn't seem to be working

### ISSUE THREAD

**Issue by jerrylin3321** [usgs/dataRetrieval#1]
**Describe the bug**
I'm trying any of the example requests in the documentation for findNLDI. All of them return the error message: 

```Error in request(method = y$method %||% x$method, url = y$url %||% x$url, : is.character(url) is not TRUE
Request failed [ERROR]. Retrying in 1.6 seconds...
Error in request(method = y$method %||% x$method, url = y$url %||% x$url, : is.character(url) is not TRUE
Request failed [ERROR]. Retrying in 1.9 seconds...
Error in request(method = y$method %||% x$method, url = y$url %||% x$url,  : 
  is.character(url) is not TRUE
```
**To Reproduce**

```r
library(dataRetrieval)
findNLDI(comid = 101)
```

**Expected behavior**
I expected this to return me data about the feature with comid = 101.

**Session Info**
Please include your session info:
```
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       Ubuntu 18.04.5 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_US:                      
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Chicago             
 date     2021-06-02   
```

**Comment by ldecicco-USGS** [comment]
What version of `dataRetrieval` are you using? 
```r
packageVersion("dataRetrieval")
```

And also....do you have the `sf` package installed?
```r
packageVersion("sf")
```
(If you didn't have that installed, install it and let me know if you still get the error).

Agreed that the error is not helpful...I am not seeing the same behavior, so I guess it's not the service behind the code.

```r
dataRetrieval::findNLDI(comid = 101)
Simple feature collection with 1 feature and 3 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: -94.64845 ymin: 31.0838 xmax: -94.62997 ymax: 31.09915
Geodetic CRS:  WGS 84
# A tibble: 1 x 4
  sourceName   identifier comid 
```

**Comment by jerrylin3321** [comment]
Here are the package versions:
> packageVersion("dataRetrieval")
[1] ‘2.7.7’
> packageVersion("sf")
[1] ‘0.9.4’

That's weird that the bug is only occurring on my end...

**Comment by ldecicco-USGS** [comment]
I guess to check for firewall issues....can you see some JSON here:
https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/101/?f=json
?

**Comment by jerrylin3321** [comment]
Yep — I can see the JSON at that link.

**Comment by ldecicco-USGS** [comment]
@dblodgett-usgs  or @mikejohnson51 ...any ideas on what might be happening?

**Comment by dblodgett-usgs** [comment]
I don't see this behavior either. I don't have access to R 3.6.2 and sf 0.9.4 is from June 2020. I would suggest updating sf at the least and seeing if it fixes the issue.

**Comment by mikejohnson51** [comment]
To offer a third check, I also don't see this behavior. 

``` r
dataRetrieval::findNLDI(comid = 101)
#> Simple feature collection with 1 feature and 3 fields
#> Geometry type: LINESTRING
#> Dimension:     XY
#> Bounding box:  xmin: -94.64845 ymin: 31.0838 xmax: -94.62997 ymax: 31.09915
#> Geodetic CRS:  WGS 84
#> # A tibble: 1 x 4
#>   sourceName   identifier comid                                         geometry
#>   <chr>        <chr>      <chr>                                 <LINESTRING [°]>
#> 1 NHDPlus com… 101        101   (-94.64845 31.09915, -94.64803 31.09871, -94.64…
```

<sup>Created on 2021-06-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jerrylin3321** [comment]
Hm, ok, do you think being on a VPN could affect anything? Although I was still able to see the JSON in the link you sent me on the VPN.

**Comment by mikejohnson51** [comment]
In my GIS class I did have a few students outside the US who had weird issues with VPNs and internet access for US federal data and GitHub - NLDI included.

**Comment by dblodgett-usgs** [comment]
You could try `sf::read_sf("https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/101/?f=json")` and see if it's something going on with that version of sf or something in how we are calling sf from dataRetrieval.

**Comment by jerrylin3321** [comment]
On sf version 0.9.4, `sf::read_sf("https://labs.waterdata.usgs.gov/api/nldi/linked-data/comid/101/?f=json")` works fine, I got an output.

**Comment by ldecicco-USGS** [comment]
You might want to check if there's a proxy server set up at your work:
```
curl::ie_proxy_info()
```

If there does seem to be one, you could try something like:
```r
library(httr)
set_config(use_proxy(url="abc.com",port=8080))
```

I'm vaguely remembering this from (scroll down to the bottom...):
https://github.com/USGS-R/dataRetrieval/issues/270

**Comment by jerrylin3321** [comment]
Hm, `curl::ie_proxy_info()` returns NULL so it doesn't look like there's a proxy server.

**Comment by jerrylin3321** [comment]
Ah I upgraded to R 4.0.2 and it fixed the issue. Maybe it was something with `httr` that wasn't working right with R 3.6.2. Anyway, thanks for the help!
