### ISSUE TITLE
Order of Sites returned by findNLDI

### ISSUE THREAD

**Issue by jerrylin3321** [usgs/dataRetrieval#2]
**What is your question?**
I had a quick question — when performing findNLDI calls to get Water Quality Portal sites, I was wondering if there's any specific order in which sites are returned from these calls. For the project I'm working on, I'm trying to feed in a set of coordinates and then find the closest upstream and downstream water monitoring facility. Right now, I can't seem to figure out what order sites are returned in. Thank you for the help!

**To Reproduce**
If possible, narrow down the question to a `dataRetrieval` query:

```r
ga_monitors <- findNLDI(location = c(-84.33160, 33.84590), nav = c("UM","DM"), 
         find = "wqp", distance_km = 5)
```

**Comment by ldecicco-USGS** [comment]
I'm not sure if @dblodgett-usgs and @mikejohnson51 follow this repo, so I'm tagging them to make sure they see the question!

**Comment by dblodgett-usgs** [comment]
Thanks for the heads up, @ldecicco-USGS -- I had my watch settings turned down to "mentions" -- am no a full watcher.

@jerrylin3321 -- for performance reasons, the NLDI does not order the response intentionally. Whatever order you get is the order that the data are returned from the query. 

If you need upstream / downstream order, you will need to pull in some additional information. Specifically, you need the "hydrosequence" attribute which indicates upstream (larger) -- downstream (smaller) sort order. 

This is something we've discussed adding to the NLDI responses (https://github.com/ACWI-SSWD/nldi-services/issues/162) but it has not made it into the system. 

If you'd like to get the hydrosequence values, you can pull them from the files in this hydroshare item:

```
Johnson, J. M. (2021). NHDPlus Value Added Attributes - no geometries, HydroShare, http://www.hydroshare.org/resource/6092c8a62fac45be97a09bfd0b0bf726
```

These can also be retrieved in R with: https://usgs-r.github.io/nhdplusTools/reference/get_vaa.html -- note that nhdplusTools is not on cran temporarily so you will need to install from github.

**Comment by jerrylin3321** [comment]
Got it, thank you!
