### ISSUE TITLE
Retrieving UV/DV data for NWISWeb access of WSC or USGS only

### ISSUE THREAD

**Issue by wsyoung-usgs** [usgs/dataRetrieval#4]
I've noticed that I can't retrieve NWIS time series data using readNWISuv if the datasets are set to USGS or WSC only.  

I thought I was able to do this in the past while on the USGS network or VPN but wasn't sure.  I couldn't find anything in the documentation regarding access levels = 2 or 3 instead of 0 (public).

Thanks,
Wendi

**Comment by ldecicco-USGS** [comment]
If you are on the network or VPN'ed, you should be able to:
```
library(dataRetrieval)
setAccess("internal")
x <- readNWISuv(....)
```
Note that won't come back with all private data, only that which is available via NWIS.

Let me know if that doesn't work (especially if it *had* worked in the past)
